language: cpp
dist: bionic
sudo: required
services: [ docker ]
git: { depth: false }
os: linux # default build params for matrix
compiler: gcc
cache: ccache

env:
  global:
  - CCACHE_SLOPPINESS=time_macros
  - CMAKE_BUILD_PARALLEL_LEVEL=4
  - MAKEFLAGS=-j$CMAKE_BUILD_PARALLEL_LEVEL
  - BUILD_TYPE=$(if [[ "$TRAVIS_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then if [[ "$TRAVIS_TAG" =~ -[a-z] ]]; then echo RelWithDebInfo; else echo Release; fi; else echo Debug; fi)
  matrix: # targets for linux
  # Ubuntu
  - OS=ubuntu DIST=eoan
  - OS=ubuntu DIST=bionic
  - OS=ubuntu DIST=xenial.16.04
  # Debian
  # - OS=debian DIST=buster # see issue #1331 on GitHub
  - OS=debian DIST=stretch
  - OS=debian DIST=jessie
  # Fedora
  - OS=fedora DIST=31
  # Open SuSe
  # - OS=opensuse # see issue #1903 on GitHub
  - OS=opensuse DIST=42.2
  # Arch Linux
  #- OS=archlinux
  # elementary OS
  - OS=el DIST=8
  # Linux Mint
  - OS=linuxmint DIST=tricia
  - OS=linuxmint DIST=tina
  - OS=linuxmint DIST=tessa
  - OS=linuxmint DIST=tara
  - OS=linuxmint DIST=sylvia

matrix:
  fast_finish: true
  include: # add non-linux targets
  #- { os: osx, osx_image: xcode11.3.1, env: OS=macos DIST=10.14 }
  #- { os: osx, osx_image: xcode11.2.1, env: OS=macos DIST=10.14 }
  #- { os: osx, osx_image: xcode10.1, env: OS=macos DIST=10.14 } 
  #- { os: osx, osx_image: xcode10.1, env: OS=macos DIST=10.13 } 
  - { os: osx, osx_image: xcode10.1, env: OS=macos DIST=10.12 }
  - stage: nightly # used only to tag and trigger nightly build
    sudo: false
    cache: pip
    services: [ ]
    git: { submodules: false, depth: 10 }
    install: skip
    before_script:
    - git config --global credential.helper store
    - echo "https://$GitHub_auth_token:x-oauth-basic@github.com" >$HOME/.git-credentials
    - git config --global user.email "nobody@no.mail"
    - git config --global user.name "Travis CI"
    script:
    - git tag -f nightly && git push -f --tags
    after_success: skip
    deploy: skip
  allow_failures:
  - env: debian DIST=jessie
  - env: debian DIST=stretch
  - env: debian DIST=buster
  - env: debian DIST=bullseye
  - env: ubuntu DIST=xenial
  - env: ubuntu DIST=zesty
  - env: ubuntu DIST=bionic
  - env: ubuntu DIST=disco
  - env: ubuntu DIST=eoan
  - env: fedora
  - env: fedora DIST=30
  - env: fedora DIST=31
  - env: opensuse
  - env: opensuse DIST=15.1
  - env: opensuse DIST=42.2
  - env: opensuse DIST=42.3
  - env: archlinux
  - env: el DIST=7
  - env: el DIST=8
  - env: linuxmint DIST=sylvia
  - env: linuxmint DIST=tara
  - env: linuxmint DIST=tessa
  - env: linuxmint DIST=tina
  - env: linuxmint DIST=tricia

stages:
  - name: nightly
    if: type IN (api, cron)
  - name: test
    if: NOT type IN (api, cron)

install: |-
  case $TRAVIS_OS_NAME in
    linux)
      DOCKER=moneymanagerex/mmex_build_env:$OS${DIST:+.$DIST}${ARCH:+.$ARCH}
      ccache -cs || true
      docker pull ${DOCKER}
      docker build dockers/$OS${DIST:+.$DIST}${ARCH:+.$ARCH} --cache-from ${DOCKER} -t ${DOCKER}
      ;;
    osx)
      export MACOSX_DEPLOYMENT_TARGET=$DIST
      brew update-reset && brew bundle --verbose --file=util/Brewfile
      brew link gettext --force
      ccache -cs && export PATH="/usr/local/opt/ccache/libexec:$PATH"
      cd $HOME
      curl -fsSL -O https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
      tar xzf wxWidgets-*.tar.bz2
      cd wxWidgets-3.1.3
      ./configure --disable-shared --enable-cxx11 --with-macosx-version-min=$MACOSX_DEPLOYMENT_TARGET --without-libtiff
      make install
      ;;
  esac

before_script:
- cd $TRAVIS_BUILD_DIR/src/db
- python ../../util/sqlite2cpp.py ../../database/tables_v1.sql && rm -f sql*.sql *.mmdbg
- python ../../util/sqliteupgrade2cpp.py ../../database
- cd ../.. && mkdir build && cd build

script: |-
  CMAKE_CMD="cmake ${ARCH:+-DCMAKE_TOOLCHAIN_FILE=util/toolchain-$TRAVIS_OS_NAME-$ARCH.cmake} -DCMAKE_BUILD_TYPE=$BUILD_TYPE .."
  case $TRAVIS_OS_NAME in
    linux)
      chmod -fR a+rwX $HOME/.ccache
      docker run -it --rm -w /moneymanagerex/build -e MAKEFLAGS \
                 -v $HOME/.ccache:/root/.ccache \
                 -v $TRAVIS_BUILD_DIR:/moneymanagerex ${DOCKER} \
        bash -c "$CMAKE_CMD -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cmake --build . --target package && eval \$MMEX_INST_CMD"
      ;;
    osx)
      export CXXFLAGS=-stdlib=libc++ # exports required by Xcode 10 or later
      export LDFLAGS=-stdlib=libc++
      $CMAKE_CMD -G Xcode && cmake --build . --target package --config $BUILD_TYPE -- \
        CC=/usr/local/opt/ccache/libexec/clang \
        CPLUSPLUS=/usr/local/opt/ccache/libexec/clang++ | \
        xcpretty -c -f `xcpretty-travis-formatter`; test ${PIPESTATUS[0]} -eq 0
      ;;
  esac

notifications: # set notification options
  email:
    recipients:
      - developers@moneymanagerex.org
    on_success: change # change is when the repo status goes from pass to fail or vice versa
    on_failure: always

after_success:
- ccache -s || true
# Rename mac packages
- if [ $TRAVIS_OS_NAME = osx ]; then
    for p in *.dmg; do mv -v $p ${p%Darwin.*}$OS$DIST.dmg; done; fi

# Set encrypted variable 'GitHub_auth_token' in Travis repo settings to deploy packages
# for tagged commits to GitHub Releases.
# Set encrypted variable 'PACKAGECLOUD_TOKEN' in Travis repo settings to deploy packages
# for tagged commits to packagecloud repo.
deploy:
- provider: releases
  api_key: $GitHub_auth_token
  file_glob: true
  file: $TRAVIS_BUILD_DIR/build/*.{deb,rpm,dmg,txz,pkg.tar.xz}
  skip_cleanup: true
  prerelease: true
  overwrite: true
  on: # Set deploy conditions
      # Deploy only when tag is specified
      tags: true
      # and only when API token is set
      condition: "${#GitHub_auth_token} != 0"
- provider: packagecloud
  repository: ${TRAVIS_REPO_SLUG#*/}
  username: ${TRAVIS_REPO_SLUG%/*}
  token: $PACKAGECLOUD_TOKEN
  dist: $OS/$DIST
  package_glob: $TRAVIS_BUILD_DIR/build/*.{deb,rpm}
  skip_cleanup: true
  on: # Set deploy conditions
      # Deploy only when tag is specified
      tags: true
      # and only packages generated by gcc from Linux
      # and only when API token is set
      condition: "$TRAVIS_OS_NAME = linux && ${#DIST} != 0 && $OS != slackware && ${#PACKAGECLOUD_TOKEN} != 0 && $TRAVIS_TAG != nightly"
